### ISSUE TITLE
pin and skewer

### ISSUE THREAD

**Issue by puspraj-india** [lichess-org/compression#5]
Flag of pin and skewer should be not checked if no bishops , no rooks and no Queen are present

**Comment by ddugovic** [comment]
Thanks for the suggestion.  95%+ of positions have a bishop, rook, or queen so I assume adding extra conditions would degrade performance:

https://github.com/lichess-org/compression/blob/25516fb9bce0c0a39ca68cde2e6eaeebc12823d3/src/main/java/game/Board.java#L222-L237

Perhaps short-circuit evaluation might improve performance, for example:

`(this.rooks ^ this.queens) & Bitboard.rookAttacks(king, 0)`

EDIT: Technically, short-circuit evaluation doesn't work, but maybe there's a more complex way to make this work: https://stackoverflow.com/a/8759917

**Comment by ddugovic** [comment]
On my PC, the proposed change is a negative 20% speedup.
