### ISSUE TITLE
Feature-Request: Tactic Problem reporting.

### ISSUE THREAD

**Issue by suryaanshah** [lichess-org/compression#9]
Tactics/Puzzles on lichess are taken from it's database, so the reply/continuing move of the puzzle is the move played in the puzzle.
However, the issue with this is, even if the first move is the best(according to the computer/stockfish chess engine), the move that opponent takes sometimes isn't the best. So in a way, we are expected to expect that the opponent will move do a blunder and then we would react to it.
Example:
![image](https://user-images.githubusercontent.com/47082682/109319388-d29d5d80-7874-11eb-9906-d6987c7f0d6a.png)
The green lines show the move sequence of the puzzle. We clearly can see that bishopC4(by black) is a blunder and we should not expect the player to do so, however, the puzzle is making up expect it.

There are 2 solutions in my head(relatively difficult but better, and relatively easier but not the best):
1. Computer shall analyse such games and do the tactically best move omitting the blunder made by the player.
2. There could be sub-forum, wherein, people can submit such puzzles and then, the puzzle could be removed or omitted.

**Comment by thomas-daniels** [comment]
This repository is specific for the algorithms of clock and move compression - are you sure you came to the right place?
